apiVersion: apps/v1
kind: Deployment
metadata:
  name: the-deployment
spec:
  template:
    spec:
      containers:
        - name: the-container
          env:
            - name: REFERENCE_NUMBER
              valueFrom:
                configMapKeyRef:
                  name: the-map
                  key: referenceNumber
